language: go

go:
  - "1.5.1"

env:
  global:
    - SSH_KEY=".id_rsa"
    - GIT_NAME="IX Deployer"
    - GIT_EMAIL="ix-stockholm@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="source"

before_install:
  - openssl aes-256-cbc -K $encrypted_e43b78cad7fe_key -iv $encrypted_e43b78cad7fe_iv -in .id_rsa.enc -out .id_rsa -d
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended

before_script:
  - go get -u -v github.com/spf13/hugo

script:
  - make install-theme
  - hugo

after_success:
  - echo "ix-sthlm.github.io" > ./public/CNAME
  - ./.deploy.sh
