language: tex
os: linux

env:
  global:
    - SSH_KEY=".travis/id_rsa"
    - GIT_NAME="IX Deployer"
    - GIT_EMAIL="ix-stockholm@gmail.com"
    - SOURCE_DIR="result"
    - DEPLOY_BRANCH="source"

before_install:
  - openssl aes-256-cbc -K $encrypted_e43b78cad7fe_key -iv $encrypted_e43b78cad7fe_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d

install:
  - curl https://raw.githubusercontent.com/pallavagarwal07/NixCI/master/travis-tests/install-nix.sh | sed 's/sudo/#sudo/' | bash

script:
  - . /home/"${USER}"/.nix-profile/etc/profile.d/nix.sh
  - nix-build -j20 .

after_success:
  - ./.travis/deploy.sh

# Build notifications in IRC
notifications:
  irc:
    channels:
      - "irc.oftc.net#ix"
    template:
      - "%{repository}#%{build_number} (%{commit} on %{branch} by %{author} with message \"%{commit_subject}\"): %{message} Details at %{build_url}"
    use_notice: true
    skip_join: true
