baseurl = "https://ix.ufs.se/"
title = "IX Stockholm"
theme = "hyde-x"
paginate = 10
DefaultContentLanguage = "sv"

[author]
    name = "IX Sthlm"

[taxonomies]
    category = "categories"
    author = "authors"

[params]
    github = "https://github.com/ix-sthlm/"
    meetup = "https://meetup.com/IX-Stockholm"
    rss = true
    sidebar_license_page = false

[languages]
    [languages.sv]
        languageCode = "sv-se"

        [languages.sv.permalinks]
            post = "/blog/:year/:month/:day/:title/"

        [languages.sv.params]
            home = "Blogg"
            tagline = "Mest på UFS"

        [[languages.sv.menu.main]]
            name = "Projekt"
            url = "/projects/"

        [[languages.sv.menu.main]]
            name = "Om oss"
            url = "/about/"

        [[languages.sv.menu.main]]
            name = "Kontakta oss"
            url = "/contact/"

        [[languages.sv.menu.main]]
            name = "Hitta hit"
            url = "/visit/"

        [[languages.sv.menu.main]]
            name = "Kalender"
            url = "/calendar/"

        [[languages.sv.menu.main]]
            name = "Bli medlem"
            url = "/membership/"
