baseurl = "https://ix.ufs.se/"
title = "IX Stockholm"
languageCode = "sv-se"
theme = "hyde-x"
paginate = 10

[author]
    name = "IX Sthlm"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"
    author = "authors"

[params]
    tagline = "Mest på UFS"
    home = "Blogg"
    github = "https://github.com/ix-sthlm/"
    rss = true
    sidebar_license_page = false

[[menu.main]]
    name = "Projekt"
    url = "/projects/"

[[menu.main]]
    name = "Om oss"
    url = "/about/"

[[menu.main]]
    name = "Kontakta oss"
    url = "/contact/"
