name: "Publish site"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build and publish site"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # Build site
      - name: Build site
        run: nix-build default.nix

      # Deploy the build artifact to another branch
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./result
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Notify IRC
      - name: Notify IRC
        uses: rectalogic/notify-irc@v1
        with:
          server: irc.oftc.net
          port: 6697
          tls: true
          channel: '#ix'
          notice: true
          nickname: ix-gh-deploy
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }} ${{ join(github.event.commits.*.message) }}

          # Old travis template:
          # "%{repository}#%{build_number} (%{commit} on %{branch} by %{author} with message \"%{commit_subject}\"): %{message} Details at %{build_url}"
